name: Pylint Code Analysis

on:
  push:
    branches: [ main ] # Analyse uniquement les push sur la branche principale
  pull_request:
    branches: [ main ] # Analyse aussi les pull requests vers la branche principale

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"] # Tu peux ajuster ces versions selon tes besoins

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Méthode simplifiée pour mettre en cache les dépendances

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Installe les dépendances de ton projet à partir de requirements.txt
        pip install -r requirements.txt

    - name: Analysing the code with Pylint
      run: |
        pylint $(git ls-files '*.py')
