name: Simple Build Test

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Essayer avec Python 3.11 au lieu de 3.12
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Test import
      run: |
        python -c "import giveaway_ig; print('Import successful')"
        
    - name: Simple build test (without data files)
      run: |
        pyinstaller --onefile --name="Giveaway_IG_Simple" giveaway_ig.py --noconfirm
        
    - name: Check if executable was created
      run: |
        if [ -f "dist/Giveaway_IG_Simple" ]; then
          echo "✅ Executable created successfully"
          ls -la dist/
        else
          echo "❌ Executable not found"
          exit 1
        fi
        
    - name: Test with data files
      run: |
        pyinstaller --onefile --name="Giveaway_IG_Full" --add-data "config.ini:." --add-data "traduction.json:." --add-data "List-Uncheck.csv:." giveaway_ig.py --noconfirm
        
    - name: Check full executable
      run: |
        if [ -f "dist/Giveaway_IG_Full" ]; then
          echo "✅ Full executable created successfully"
          ls -la dist/
        else
          echo "❌ Full executable not found"
          ls -la dist/ || echo "No dist directory"
        fi